public class twodimelist 
{
    public static void two()
    {
/*       list<list<integer>> l1 = new list<list<integer>>{new list<integer>{1,2,3},
                                                         	new list<integer>{4,5,6},
                                                                new list<integer>{7,8,9}};*/
        list<list<list<integer>>> l1 = new list<list<list<integer>>>{};
    }

}